from . import ISendMail
from . import SendMail
from . import IContinuousRecording
from . import ContinuousRecording
from . import IEventRecording
from . import EventRecording
from . import ITimerRecording
from . import TimerRecording
from . import ITimerEventRecording
from . import TimerEventRecording
from . import IDetectMotion
from . import DetectMotion
from . import IAnalyzeVideo
from . import AnalyzeVideo